dash_app_id = "dash-app-id"
tab_one_id = "tab-one-id"
title_page_id = "title-page-id"
all_components_div_id = "full-div-id"
all_components_but_indstructions_div_id = "api-pull-components-div-id"
api_pull_component_id = "top-div-id"

# API AND EXCEL Import Section Components
imported_file_movie_list_id = "store-movie-list-id"
imported_movie_data_id = "store-movie-data-id"
file_upload_loading_id = "loading-excel-id"
api_import_loading_id = "loading-api-id"
upload_file_btn_id = "upload-movie-list-btn-id"
api_import_btn_id = "import-movies-api-btn-id"
api_import_modal_title_id = "pull-movie-modal-title-id"
api_import_modal_message_id = "pull-movie-modal-message-id"
api_import_modal_position_id = "pull-movie-modal-position-id"
file_upload_modal_title_id = "upload-movie-title-excel-id"
file_upload_modal_message_id = "upload-movie-title-excel-modal-message-id"
file_upload_modal_position_id = "upload-movie-title-excel-modal-position-id"
app_title_form_id = "welcome-message-form-id"
instructions_text_id = "instructions-for-app-id"
total_time_box_id = "total-time-box-id"
avg_time_box_id = "avg-time-box-id"
movie_file_and_api_form_id = "choose-movies-form-id"
instructions_div_id = "instructions-form-id"
upload_and_api_div_id = "tab-one-buttons-div-id"
button_labels_div_id = "buttons-label-id"
total_time_div_id = "total-time-div-id"
total_time_label_id = "total-time-label-id"
avg_time_div_id = "avg-time-div-id"
avg_time_label_id = "avg-time-label-id"

# MODEL SECTION COMPONENTS
model_prediction_btn_id = "model-pred-btn-id"
export_results_btn_id = "export-preds-btn-id"
results_table_id = "prediction-result-table-id"
model_title_div_id = "model-section-title-div-id"
model_components_div_id = "model-components-div-id"
graph_div_id = "graph-div-id"
run_model_div_id = "run-div-id"
model_btns_div_id = "model-buttons-div-id"
predict_div_id = "predict-div-id"
export_div_id = "export-div-id"
model_coefs_div_id = "model-coefficients-graph-id"
result_table_div_id = "result-table-div-id"
